class Config:
    TABLE_CANDIDAT = "Candidat"
    TABLE_CANDIDAT_ID = "candidat_id"
    TABLE_CANDIDAT_NOM = "candidat_nom"
    TABLE_CANDIDAT_PRENOM = "candidat_prenom"

    TABLE_ELECTION = "Election"
    TABLE_ELECTION_ID = "election_id"
    TABLE_ELECTION_ANNEE = "election_annee"
    TABLE_ELECTION_TOUR = "election_tour"

    TABLE_CIRCONSCRIPTION = "Circonscription"
    TABLE_CIRCONSCRIPTION_ID = "circ_el_id"
    TABLE_CIRCONSCRIPTION_NUMDPT = "numpdpt"
    TABLE_CIRCONSCRIPTION_NOMDPT = "nomdpt"
    TABLE_CIRCONSCRIPTION_NUMCIRC = "numcirc"
    TABLE_CIRCONSCRIPTION_INSCRITS = "inscrits"
    TABLE_CIRCONSCRIPTION_VOTANTS = "votants"
    TABLE_CIRCONSCRIPTION_EXPRIMES = "exprimes"
    TABLE_CIRCONSCRIPTION_BLANCSETNULS = "blancs_et_nuls"

    TABLE_FAIT = "Fait"
    TABLE_FAIT_IDELECTION = "id_election"
    TABLE_FAIT_IDCIRCONSCRIPTION = "id_circ"
    TABLE_FAIT_IDCANDIDAT = "id_candidat"
    TABLE_FAIT_NBVOTE = "nbvote"
    TABLE_FAIT_PARTI_POLITIQUE = "parti_politique"

    MVIEW_INFOSELECTIONDPT = "INFOS_ELECTIONS_DEPARTEMENT"
    MVIEW_INFOSELECTIONDPT_IDELECTION = "id_election"
    MVIEW_INFOSELECTIONDPT_ELECTIONANNEE = "election_annee"
    MVIEW_INFOSELECTIONDPT_ELECTIONTOUR = "election_tour"
    MVIEW_INFOSELECTIONDPT_NUMDPT = "numdpt"
    MVIEW_INFOSELECTIONDPT_VOTESVALIDETOTAL = "VOTES_VALIDE_TOTAL"
    MVIEW_INFOSELECTIONDPT_BLANCSETNULTOTAL = "BLANCS_ET_NULS_TOTAL"
    MVIEW_INFOSELECTIONDPT_VOTESTOTAL = "VOTES_TOTAL"
    MVIEW_INFOSELECTIONDPT_INSCRITSTOTAL = "INSCRITS_TOTAL"
    MVIEW_INFOSELECTIONDPT_ABSTENTION = "ABSTENTION"

    MVIEW_INFOSELECTIONNATIONAL = "INFOS_ELECTIONS_NATIONAL"
    MVIEW_INFOSELECTIONNATIONAL_IDELECTION = "id_election"
    MVIEW_INFOSELECTIONNATIONAL_ELECTIONANNEE = "election_annee"
    MVIEW_INFOSELECTIONNATIONAL_ELECTIONTOUR = "election_tour"
    MVIEW_INFOSELECTIONNATIONAL_VOTESVALIDETOTAL = "VOTES_VALIDE_TOTAL"
    MVIEW_INFOSELECTIONNATIONAL_BLANCSETNULTOTAL = "BLANCS_ET_NULS_TOTAL"
    MVIEW_INFOSELECTIONNATIONAL_VOTESTOTAL = "VOTES_TOTAL"
    MVIEW_INFOSELECTIONNATIONAL_INSCRITSTOTAL = "INSCRITS_TOTAL"
    MVIEW_INFOSELECTIONNATIONAL_ABSTENTION = "ABSTENTION"

    MVIEW_VOTESCANDIDATNATIONAL = "VOTE_CANDIDAT_NATIONAL"
    MVIEW_VOTESCANDIDATNATIONAL_IDELECTION = "id_election"
    MVIEW_VOTESCANDIDATNATIONAL_ANNEE = "election_annee"
    MVIEW_VOTESCANDIDATNATIONAL_TOUR = "election_tour"
    MVIEW_VOTESCANDIDATNATIONAL_IDCANDIDAT = "id_candidat"
    MVIEW_VOTESCANDIDATNATIONAL_VOTES = "votes"


    @staticmethod
    def val_to_str(val) -> str:
        string = str(val)
        # https://stackoverflow.com/a/9596819
        string = string.replace("'", "''")
        return string