= X2I1010 - Projet : Analyse des tendances politiques aux élections présidentielles de 1965 à 2017

== Contributeurs

DELI Dro Kieu
GEORGES Thomas
GICQUEL Mathieu
TIOUS Amar

== Intégration des données

La transformation des données brut en format SQL est réalisé grâce au script Python elecpresi2sql.
Pour plus d'information sur la génération du SQL, allez dans le dossier elecpresi2sql puis suivez les instructions du README

== Droits d'accès
Pour ajouter les droits d'accès à la base de données, utilisez le script VPD disponible dans le dossier VPD.
Pour tester les droits d'accès à la base de données, utilisez le script TEST_VPD disponible dans le dossier VPD.

== Sources des données

Les données proviennent des sources suivantes :

* https://www.data.gouv.fr/fr/datasets/elections-presidentielles-1965-2012-1/ (Mis à jour le 13 février 2016)
* https://www.data.gouv.fr/fr/datasets/election-presidentielle-des-23-avril-et-7-mai-2017-resultats-definitifs-du-1er-tour-par-bureaux-de-vote/ (Mis à jour le 27 avril 2017)
* https://www.data.gouv.fr/fr/datasets/election-presidentielle-des-23-avril-et-7-mai-2017-resultats-definitifs-du-2nd-tour-par-bureaux-de-vote/ (Mis à jour le 11 mai 2017)

Les fichiers ont été adaptés afin de correspondre à nos besoins.

== Licence

https://spdx.org/licenses/ODbL-1.0.html#licenseText
