-- Evolution du nombre d'inscrits dans le département 35

SELECT
t.ELECTION_ANNEE,
t.NUMDPT,
(t.INSCRITS_TOTAL),
LAG((t.INSCRITS_TOTAL),1) over (ORDER BY t.NUMDPT) as inscrits_previous_year
FROM
INFOS_ELECTIONS_DEPARTEMENT t
WHERE
t.ELECTION_TOUR = 1
AND t.NUMDPT = '35'
ORDER BY t.NUMDPT, t.ELECTION_ANNEE;