-- Récupérer les informations par élection

SELECT
   ID_ELECTION,
   SUM(NBVOTE) AS VOTES_VALIDE_TOTAL,
   SUM(c.BLANCS_ET_NULS) as BLANCS_ET_NULS_TOTAL,
   (SUM(NBVOTE) + SUM(c.BLANCS_ET_NULS)) as VOTES_TOTAL,
   SUM(c.INSCRITS) as INSCRITS_TOTAL
FROM
    FAIT f,
    ELECTION e,
    CIRCONSCRIPTION c
WHERE
    f.ID_ELECTION  = e.ELECTION_ID
    AND c.CIRC_EL_ID = f.ID_CIRC
GROUP BY  ( ID_ELECTION);